# Generated by Django 5.2.17 on 2026-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
